### ISSUE TITLE
Script for generating test data

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/digestiflow-cli#7]
The bcl2fastq v2.20 tarball contains a script for creating test data. We should use this in CI for generating test data on the fly, at least for those where we also have in-house data available.

- NextSeq 500 data
- HiSeq 2500 data
- HiSeq 4000 data
- NovaSeq data

@messersc can you have a look at this Illumina-provided script and see how we could create it? We would have to write compatible XML files on our own, though.

**Comment by messersc** [comment]
This is quite straight-forward, as the script can be run as is or with minor changes (e.g. reduce number of clusters for faster running time, enable/disable concatenated bcls from command line).

Writing conforming dummy xmls is indeed necessary.

**Comment by holtgrewe** [comment]
OK, @messersc I'll do this, need this for the manual also.
